# -*- coding: utf-8 -*-
"""add.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_6_Wlt_BjpWbLEBnEb7JtKQcjkQY_zHJ
"""

def add(x,y):
    return(x+y)