# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_6_Wlt_BjpWbLEBnEb7JtKQcjkQY_zHJ
"""

print("C A L C U L A T O R")
x=int(input("enter the first number:"))
y=int(input("enter the second number:"))
print("\n1.Addition(+)\n2.Subtraction(-)\n3.Division(/)\n4.Multiplication(*)\n5.Exit\n")
ch=int(input("Choose Operand:"))
if(ch==1):
    a=add(x,y)
    print("added value is",a)
elif(ch==2):
    a=sub(x,y)
    print("subtracted value is",a)
elif(ch==3):
    a=div(x,y)
    print("Divided value is",a)
elif(ch==4):
    a=mul(x,y)
    print("divided value is",a)
else:
    print("invalid")