# -*- coding: utf-8 -*-
"""mul.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_6_Wlt_BjpWbLEBnEb7JtKQcjkQY_zHJ
"""

def mul(x,y):
    return x*y